FROM nginx:alpine

# Copy the web app's files into the container
COPY dataviewer-src/ /usr/share/nginx/html/

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 8090 for the web server
EXPOSE 8090

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]